Allow users to be added by github username

diff --git a/server b/server
--- a/server
+++ b/server
@@ -114,29 +114,60 @@ restart_service() {
 
 add_user() {
 	while [[ $# -gt 0 ]] ; do
-	    arg="$1" ; shift
-	    case $arg in
-	        -f|--sshkeyfile) sshkeyfile="$1" ; shift;;
-	        --sshkeyfile=*) sshkeyfile="${arg#*=}" ; sshkeyfile="${sshkeyfile/#\~/$HOME}";;
+		arg="$1" ; shift
+		case $arg in
+			-f|--sshkeyfile) sshkeyfile="$1" ; shift;;
+			--sshkeyfile=*) sshkeyfile="${arg#*=}" ; sshkeyfile="${sshkeyfile/#\~/$HOME}";;
 			-u|--user) new_user=$1 ; shift;;
 			--user=*) new_user=${arg#*=};;
+			--github-username) github_username=$1 ; shift;;
+			--github-username=*) github_username=${arg#*=};;
 			*) echo "Unknown argument: $arg" ; exit 1;;
-	    esac
+		esac
 	done
-    if [[ -z $new_user ]] || [[ -z "$sshkeyfile" ]] ; then
+    if [[ -z $new_user || -z "$sshkeyfile" ]] && [[ -z $github_username ]] ; then
 		cat <<-.
-		Add a new admin user to the server.
-		A password will be randomly generated for the new user.
+		Add a new admin user to the server. A password will be randomly
+		generated for the new user.
 
-		-f|--sshkeyfile <sshkeyfile> -- path to the new user's public key
-		-u|--user <username>         -- username for the new user
+		Can be used by either specifying a username and public key file, or a
+		github username and the public keys will be extracted from github
+		(https://github.com/$USERNAME.keys)
+
+		-f|--sshkeyfile <sshkeyfile>  -- path to the new user's public key
+		-u|--user <username>          -- username for the new user
+		--github-username <username>  -- github username to lookup public keys;
+		                                 will also be used as server username
 
 		Examples:
 		    $(basename "$0") adduser -u sally -f ~/sallys-ssh-key.pub
 		    $(basename "$0") adduser --user=sally --sshkeyfile=~/key.pub
+		    $(basename "$0") adduser --github-username gocodeup
 		.
 		die
     fi
+
+	if [[ -n $github_username ]] ; then
+		new_user=$github_username
+		sshkeyfile=$(mktemp)
+		trap "rm -f $sshkeyfile" EXIT
+		url="https://github.com/${github_username}.keys"
+		wget -O "$sshkeyfile" "$url"
+		if [[ $? -ne 0 ]] ; then
+			echo "Error obtaining public keys for $github_username!"
+			echo "$url gave a non-200 response."
+			echo 'Aborting...'
+			exit 1
+		fi
+		if [[ ! -s $sshkeyfile ]] ; then
+			echo "Error! It looks like this user doesn't have any public keys tied to"
+			echo "their github account. Check ($url)."
+			echo 'Aborting...'
+			exit 1
+		fi
+		echo 'Downloaded public ssh key(s)!'
+	fi
+
 	if [[ ! -f "$sshkeyfile" ]]; then
 		echo 'Please enter a valid ssh key file.'
 		exit 1
@@ -161,7 +192,7 @@ add_user() {
 		[NOTICE] credentials for ${new_user} have been added to $DATA_DIR/credentials.txt
 		.
 	else
-		echo 'Uh oh, something went wrong! Check the output above and try again'
+		echo 'Uh oh, something went wrong! Check the output for details.'
 	fi
 
 }
@@ -243,7 +274,7 @@ show_usage() {
 	    upload  -f <file> [-d <destination>]
 	    restart -s <service>
 	    addkey  -f <sshkeyfile>
-	    adduser -u <username> -f <sshkeyfile>
+	    adduser [-u <username> -f <sshkeyfile>] [--github-username <username>]
 
 	help_message
 }
