Start site testing

diff --git a/test b/test
--- a/test
+++ b/test
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+fail() {
+	echo "[FAIL] $@"
+	exit 1
+}
+
 # find out where this script is located so we can be sure we're running
 # everything from the correct location
 SCRIPT_PATH=$0
@@ -22,6 +27,7 @@ if [[ ! -f $ENV_FILE ]]; then
 fi
 
 source $ENV_FILE
+source $SCRIPTS/util.sh
 
 command=$1 ; shift
 
