rename db subcommand migrate to run
we end up using this command most of the time for seeders, so let's give
it a better name

diff --git a/scripts/db b/scripts/db
--- a/scripts/db
+++ b/scripts/db
@@ -58,30 +58,30 @@ backup_db() {
     echo "$outputfile created!"
 }
 
-run_migration() {
+run_file() {
     database=$1
-    migration_file=$2
+    sql_file=$2
     if [[ -z $database ]]; then
         read -p 'database name: ' database
     fi
-    if [[ -z $migration_file ]]; then
-        read -ep 'migration file: ' migration_file
+    if [[ -z $sql_file ]]; then
+        read -ep 'sql file: ' sql_file
         # parse the home directory correctly
-        if grep '^~' <<< "$migration_file"; then
-            migration_file=$(perl -pe "s!~!$HOME!" <<< $migration_file)
+        if grep '^~' <<< "$sql_file"; then
+            sql_file=$(perl -pe "s!~!$HOME!" <<< $sql_file)
         fi
     fi
 
     # ensure file exists and is a sql file (or at least has the extension)
-    if [[ ! -f $migration_file ]]; then
+    if [[ ! -f $sql_file ]]; then
         echo 'It looks like that file does not exist! Aborting...'
-        echo "Could not find '$migration_file'! No migrations run."
+        echo "Could not find '$sql_file'! No migrations run."
         exit 1
     fi
-    grep '\.sql$' >/dev/null <<< $migration_file
+    grep '\.sql$' >/dev/null <<< $sql_file
     if [[ $? -ne 0 ]]; then
         echo 'It looks like that is not a valid SQL file! Aborting...'
-        echo "'$migration_file' does not have a '.sql' file extension."
+        echo "'$sql_file' does not have a '.sql' file extension."
         echo 'No migrations run.'
         exit 1
     fi
@@ -90,9 +90,9 @@ run_migration() {
     # make sure the nowdoc identifier doesnt clash with anything in the
     # migration
     ssh -t $user@$ip "mysql -p $database <<'xxxxxxxxxx_sql_migration_xxxxxxxxx'
-    $(cat $migration_file)
+    $(cat $sql_file)
 xxxxxxxxxx_sql_migration_xxxxxxxxx"
-    [[ $? -eq 0 ]] && echo 'Finished running migration.'
+    [[ $? -eq 0 ]] && echo 'Finished running!'
 }
 
 remove_db() {
@@ -128,7 +128,7 @@ where <command> is one of the following:
     list
     create  [dbname [dbuser]]
     backup  [dbname [outputfile]]
-    migrate [dbname [migration.sql]]
+    run     [dbname [/path/to/file.sql]]
     remove  [dbname [dbuser]]
 
 help_message
@@ -140,7 +140,7 @@ shift
 case $command in
     create)    create_db $@;;
     backup)    backup_db $@;;
-    migrate)   run_migration $@;;
+    run)       run_file  $@;;
     remove|rm) remove_db $@;;
     list|ls)   list_databases;;
     login)     login;;
